"""fayl bloklari

Revision ID: 0c4d5099b269
Revises: 9455ad7cc0ec
Create Date: 2026-09-29 02:47:45.907229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4d5099b269'
down_revision: Union[str, Sequence[str], None] = '9455ad7cc0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_blobs',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_blobs')
    # ### end Alembic commands ###
