"""bank sahələri text

Revision ID: 49fe6c7b246e
Revises: 1f261b8620e0
Create Date: 2026-09-29 03:36:23.729112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fe6c7b246e'
down_revision: Union[str, Sequence[str], None] = '1f261b8620e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_files', schema=None) as batch_op:
        batch_op.alter_column('lesson',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('bank_questions', schema=None) as batch_op:
        batch_op.alter_column('qid',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('bank_sources', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_sources', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('bank_questions', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
        batch_op.alter_column('qid',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('bank_files', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)
        batch_op.alter_column('label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
        batch_op.alter_column('lesson',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
